server:
  port: 7070
spring:
  application:
    name: TENANT-GAF-GATEWAY
#    user:
#      name: admin
#      password: 123456
  profiles:
    active: dev

gateway:
  enable: true
  lowerCaseServiceId: true
  route:
    enable: true
    redis:
      enable: false
      hostName: 127.0.0.1
      port: 6379
      #password: 123456
      maxIdle: 0
      minIdle: 0
      maxActive: 8
      databaseIndex: 0
      maxWaitMillis: -1
      timeout: 3000
      ssl: false
  #    limit:
  #      enbale: false
  #      limiterRate:
  #      limiterCapacity:


